# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
  schedule:
  - cron: '42 */12 * * *'

jobs:
  ci-msvc:
    name: CI with MSVC
    runs-on: windows-latest

    steps:
    - name: Clone GTK
      run: cd / && git clone https://gitlab.gnome.org/GNOME/gtk.git --depth 1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Python Dependencies
      run: pip install meson ninja
    - name: Prepare MSVC
      uses: bus1/cabuild/action/msdevshell@v1
      with:
        architecture: x64
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Prepare Build
      run: cd /gtk && meson setup builddir --prefix=C:/gnome -Dbuild-tests=false -Dmedia-gstreamer=disabled
    - name: Run Build
      run: cd /gtk && meson install -C builddir
